Pharap/Minesweeper

- Languages/DE-DE.h
- Languages/Languages.h
- Localisation.md
- Settings.h
Adds German translation by @Nicole_Birgel.
> Add German

- StatsState.cpp
Reorganises the stat screen to appear as:
> Wins:
> 1
>
> Losses:
> 1
As described by #7.
Closes #7.
> Reorganise stats screen

- Minesweeper/Languages/DE-DE.h
- Minesweeper/Languages/EN-AU.h
- Minesweeper/Languages/EN-GB.h
- Minesweeper/Languages/EN-LCY.h
- Minesweeper/Languages/ES-ES.h
- Minesweeper/Languages/FR-FR.h
- Minesweeper/Languages/Languages.h
Add string entry and various translations for "Themes".
Co-authored-by: Stephane C <30958385+vampirics@users.noreply.github.com>
Co-authored-by: Erwin Ried <1091420+eried@users.noreply.github.com>
Co-authored-by: Nicole Birgel <>
> Add string translations for "Themes"

- Minesweeper/Game.cpp
- Minesweeper/ThemesState.cpp
- Minesweeper/ThemesState.h
- Minesweeper/TitlescreenState.cpp
This adds a `ThemesState` class with placeholder code in preparation for adding proper themes functionality.
> Add a placeholder Themes state

- Minesweeper/ThemesState.cpp
It doesn't look particularly pretty, but it's functional, which is the main thing.
It can always be improved later.
> Add basic theme selection functionality

- Minesweeper/TitlescreenState.cpp
- Minesweeper/TitlescreenState.h
> Remove old themes easter egg

- Minesweeper/Languages/DE-DE.h
- Minesweeper/Languages/EN-AU.h
- Minesweeper/Languages/EN-GB.h
- Minesweeper/Languages/EN-LCY.h
- Minesweeper/Languages/ES-ES.h
- Minesweeper/Languages/FR-FR.h
- Minesweeper/Languages/Languages.h
Add string entry and various translations for "Graphics".
> Add translations for graphics

- Minesweeper/Credits.h
- Minesweeper/CreditsState.cpp
Adds a new "Graphics" category to the credits page.
Closes #21.
> Add credits for graphics

- Minesweeper/Utils/Checksum.h
- Minesweeper/Utils/Eeprom.h
- Minesweeper/Utils/SkullHash.h
- Minesweeper/Utils/Utils.h
Introduces three utility classes that are to be used for the save system overhaul described by #22.
> Add new utility classes

- Minesweeper/GameContext.cpp
- Minesweeper/GameContext.h
- Minesweeper/GameplayState.cpp
- Minesweeper/GameplayState.h
- Minesweeper/SaveCheckState.cpp
- Minesweeper/SaveSystem.h
- Minesweeper/SplashscreenState.cpp
- Minesweeper/StatsState.cpp
- Minesweeper/StatsState.h
This new save system will allow new save data to be added without breaking backwards compatibility.
From here on out, eeprom save data will be both forwards and backwards compatible.
Saves made by v2.0.0 will be compatible with svaes made by later versions.
Saves made by later versions will be compatible with saves made by v2.0.0
Closes #22.
> Overhaul the save system

- Minesweeper/Languages/DE-DE.h
- Minesweeper/Languages/EN-AU.h
- Minesweeper/Languages/EN-GB.h
- Minesweeper/Languages/EN-LCY.h
- Minesweeper/Languages/ES-ES.h
- Minesweeper/Languages/FR-FR.h
- Minesweeper/Languages/Languages.h
Adds the names for the different themes and the translations for those names.
> Add theme names and translations

- Minesweeper/GameContext.cpp
- Minesweeper/GameContext.h
- Minesweeper/GameStats.h
- Minesweeper/GameplayState.cpp
- Minesweeper/SaveCheckState.cpp
- Minesweeper/StatsState.cpp
- Minesweeper/ThemesState.cpp
- Minesweeper/TileGridRenderer.cpp
- Minesweeper/TitlescreenState.cpp
> Add theme saving functionality

- Minesweeper/Images/Backgrounds.h
- Minesweeper/Images/Icons.h
- Minesweeper/Images/LargeTiles.h
- Minesweeper/Images/Logos.h
- Minesweeper/Images/Tiles.h
- Minesweeper/Languages/DE-DE.h
- Minesweeper/Languages/EN-AU.h
- Minesweeper/Languages/EN-GB.h
- Minesweeper/Languages/EN-LCY.h
- Minesweeper/Languages/ES-ES.h
- Minesweeper/Languages/FR-FR.h
Add credits for graphics and localisation into the source code.
This ensures that everyone is credited even with the git information is discarded.
> Add credits to source code

- Minesweeper/SaveSystem.h
Previously the code allowed potentially invalid data to be loaded.
This fixes that by only loading the parts of the data that are confirmed to be valid.
> Fix bug in loadData function

- Minesweeper/ConfirmationMenu.h
- Minesweeper/GameplayState.cpp
Adds a small black 1x1pixel border around menu boxes as requested by @filmote.
> Add small black border around menu boxes

- Minesweeper/ThemesState.cpp
Improves the theme selection UI.
This new UI matches the original layout specified in the design documentation.
Closes #31.
> Improve theme selection UI

- Minesweeper/Utils/SkullHash.h
> Add a comment about xorshift

- Minesweeper/SaveSystem.h
Using `reinterpret_cast` in a `constexpr` context is actually illegal,
this code was only compiling because of Arduino's use of `-fpermissive`.
Closes #65.
> Fix use of reinterpret_cast in contexpr context

- Minesweeper/Images/LargeTiles.h
- Minesweeper/Images/Tiles.h
> Improve citations

- Minesweeper/Utils/SkullHash.h
> Improve Marsaglia citation
